version: '3.8'

services:
  vault:
    image: vault:1.15.2
    container_name: vault-server
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - ./vault-config.hcl:/vault/config/vault-config.hcl:ro
      - vault-data:/vault/data
      - vault-logs:/vault/logs
    environment:
      - VAULT_CONFIG_DIR=/vault/config
      - VAULT_ADDR=http://0.0.0.0:8200
    command: ["vault", "server", "-config=/vault/config/vault-config.hcl"]
    cap_add:
      - IPC_LOCK
    networks:
      - vault-network
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  vault-ui:
    image: djenriquez/vault-ui:latest
    container_name: vault-ui
    ports:
      - "8000:8000"
    environment:
      - VAULT_URL_DEFAULT=http://vault:8200
      - VAULT_AUTH_DEFAULT=USERPASS
    networks:
      - vault-network
    depends_on:
      - vault

volumes:
  vault-data:
  vault-logs:

networks:
  vault-network:
    driver: bridge
