apiVersion: v1
kind: Secret
metadata:
  name: messenger-secrets
  labels:
    app: messenger-api
type: Opaque
data:
  # Значения закодированы в base64
  # Для примера: echo -n "your-secret-key" | base64
  JWT_SECRET: eW91ci1zZWNyZXQta2V5
  DB_PASSWORD: cGFzc3dvcmQxMjM=
  API_KEY: YXBpLWtleS0xMjM0NTY=
